"""Backwards-compatibility shim.

The implementation moved to :mod:`..dispatcher`, :mod:`..decoders.*`,
:mod:`..protocols.*` and :mod:`..crc`. Existing imports from this module
continue to work via the re-exports below — new code should import from
the dedicated modules instead.
"""
from __future__ import annotations

from ..decoders.enums import (
    ACInputVoltageRange,
    BatteryType,
    BatteryTypeSetting,
    ChargerSourcePriority,
    ChargeSourcePrioritySetting,
    DeviceStatusBitsB7B0,
    DeviceStatusBitsB10B8,
    OperatingMode,
    OutputSourcePriority,
    OutputSourcePrioritySetting,
    ParallelMode,
    parse_device_status_bits_b7_b0,
    parse_device_status_bits_b10_b8,
)
from ..decoders.voltronic import (
    decode_ascii_response,
    decode_direct_response,
    decode_qbeqi,
    decode_qflag,
    decode_qid,
    decode_qmn,
    decode_qmod,
    decode_qpigs,
    decode_qpigs2,
    decode_qpiri,
    decode_qvfw,
    direct_commands,
    get_command_hex,
    get_command_name_by_hex,
    is_hex_string,
    transform_qpiri_value,
)
from ..dispatcher import (
    get_direct_data,
    set_battery_bulk_voltage,
    set_battery_charge_current,
    set_battery_float_voltage,
    set_battery_type,
    set_charge_source_priority,
    set_direct_data,
    set_direct_data_agent,
    set_max_combined_charge_current,
    set_max_utility_charge_current,
    set_output_source_priority,
    set_rated_battery_voltage,
)
from ..protocols.agent_http import AGENT_STALE_THRESHOLD_MS
from ..protocols.modbus_rtu import (
    UNIT_ID,
)

__all__ = [
    "ACInputVoltageRange",
    "AGENT_STALE_THRESHOLD_MS",
    "BatteryType",
    "BatteryTypeSetting",
    "ChargerSourcePriority",
    "ChargeSourcePrioritySetting",
    "DeviceStatusBitsB10B8",
    "DeviceStatusBitsB7B0",
    "OperatingMode",
    "OutputSourcePriority",
    "OutputSourcePrioritySetting",
    "ParallelMode",
    "UNIT_ID",
    "decode_ascii_response",
    "decode_direct_response",
    "decode_qbeqi",
    "decode_qflag",
    "decode_qid",
    "decode_qmn",
    "decode_qmod",
    "decode_qpigs",
    "decode_qpigs2",
    "decode_qpiri",
    "decode_qvfw",
    "direct_commands",
    "get_command_hex",
    "get_command_name_by_hex",
    "get_direct_data",
    "is_hex_string",
    "parse_device_status_bits_b10_b8",
    "parse_device_status_bits_b7_b0",
    "set_battery_bulk_voltage",
    "set_battery_charge_current",
    "set_battery_float_voltage",
    "set_battery_type",
    "set_charge_source_priority",
    "set_direct_data",
    "set_direct_data_agent",
    "set_max_combined_charge_current",
    "set_max_utility_charge_current",
    "set_output_source_priority",
    "set_rated_battery_voltage",
    "transform_qpiri_value",
]
